apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spesialist.intern.dev.nav.no
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    disableAutoScaling: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a" # speil-brukere-prod - har du tilgang i prod har du tilgang i dev også er tanken her
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # gammel hjemmemekka tbd-gruppe
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
          - id: "c811e9f4-26a6-43f9-b930-8c83365683a9"
          - id: "59f26eef-0a4f-4038-bf46-3a5b2f252155"
          - id: "dd4e2415-b68d-43a4-87b5-fe2ba5f1dc61"
          - id: "317665ad-1402-458e-b8e6-9cb50afc1252" # speil-brukere-dev
  accessPolicy:
    inbound:
      rules:
        - application: speil
          cluster: dev-gcp
        - application: speil-next
          cluster: dev-gcp
    outbound:
      rules:
        - application: spleis-api
          namespace: tbd
          cluster: dev-gcp
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: dev-gcp
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        databases:
          - name: spesialist
            envVarPrefix: DATABASE
            users:
              - name: spesialist-opprydding-dev
              - name: spesialist-migrering
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-v1
    - name: KODE7_SAKSBEHANDLER_GROUP
      value: c811e9f4-26a6-43f9-b930-8c83365683a9
    - name: BESLUTTER_SAKSBEHANDLER_GROUP
      value: dd4e2415-b68d-43a4-87b5-fe2ba5f1dc61
    - name: SKJERMEDE_PERSONER_GROUP
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: SAKSBEHANDLERE_MED_TILGANG_TIL_STIKKPROVER
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: SAKSBEHANDLERE_MED_TILGANG_TIL_SPESIALSAKER
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: SPLEIS_CLIENT_ID
      value: api://dev-gcp.tbd.spleis-api/.default
    - name: SPLEIS_API_URL
      value: "http://spleis-api"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_API_URL
      value: "http://digdir-krr-proxy.team-rocket.svc.cluster.local"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: AUTOMATISER_SPESIALSAK
      value: "true"
